import Sidebar from "./components/Sidebar";
import "./globals.css";
import {Poppins} from "@next/font/google";
import React from "react";
import SidebarProvider from "./context/GlobalContext";



export const poppins = Poppins({
  // Optional: Specify the weights to load
  weight: ['300','400', '500', '600', '700'],
  preload: false,
  display: "swap",
});


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",

};

export default function RootLayout({ children }) {

  return (
    <html lang="en" className={poppins.className}>
      <body>
        <SidebarProvider>
          <Sidebar />
          <div className="mx-auto w-full sm:pl-[300px] relative min-h-screen overflow-hidden flex flex-col">
            {children}
          </div>
        </SidebarProvider>

      </body>
    </html>
  );
}
