import Sidebar from "./components/Sidebar";
import "./globals.css";
import { Poppins } from "next/font/google";
import { GlobalStorage } from "./context/GlobalContext";

const poppins = Poppins({
  subsets: ["latin"],
  preload: true,
  weight: ["400", "500", "600", "700"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        <Sidebar />
        <div className="mx-auto w-full sm:pl-[300px] relative min-h-screen overflow-hidden flex flex-col">
        {children}
        </div>
      </body>
    </html>
  );
}
